@url = http://localhost:5003/curriculum
 
### 查询排课表
GET {{url}} HTTP/1.1
### 查询排课表
GET {{url}}/class/软件一班 HTTP/1.1

### 添加排课内容  
POST {{url}} HTTP/1.1 
Content-Type: application/json

# {
#     "CurriCulumData":"{\"星期一\":\"大数据开发\",\"星期二\":\"思政\",\"星期三\":\"未来方程式\",\"星期四\":\"成功者学说\",\"星期五\":\"自习\"}",
#     "AcademyInfoClassName":"软件工程学院20级软件技术1班"
# }
{
    "CurriCulumData":",,,,,,,,",
    "SpecializedName":"软件一班"
}

### 修改排课内容
PUT {{url}}/825fab73-e43d-48d4-a8d6-06e168d89c2a HTTP/1.1 
Content-Type: application/json

{
    "CurriCulumData":"星期一:社会心理学,星期二:思政,星期三:未来方程式,星期四:成功者学说,星期五:自习,星期六:自习,星期日:自习",
    "SpecializedName":"软件工程学院20级软件技术1班"
}

### 删除排课内容
DELETE {{url}}/fa4dcba5-3964-47b1-8eca-a1dcf78d2d69 HTTP/1.1

### 查询课表（根据班级，模糊查询）
GET {{url}}/软件工程学院20级软件技术1班 HTTP/1.1