@url=http://localhost:5003/questionnaire


//新增问卷调查
###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "QuestionnaireTheme" :"教师满意度调查问卷",
    "QuestionnaireTitle" : "XX学院XX月教师满意度调查问卷",
    "QuestionnaireQuestion":{
        "1":"请选择你的任课老师",
        "2":"任课老师在教学中是否保持精神饱满，仪表端庄，声音洪亮",
        "3":"每次课堂，认真讲课，课后批改作业",
        "4":"老师积极向上，带动学生学生积极性，提升学生学习兴趣",
        "5":"老师亲和力：学生对老师的喜爱度和满意度",
        "6":"能定时收取学生笔记,及时批改、总结,及时下发",
        "7":"对学生的作品教师能做到逐个打分、集中点评",
        "8":"您认为在课堂上，任课老师与同学的互动情况",
        "9":"能针对目前所学课程，您的收获如何",
        "10":"您认为课堂上的学习气氛如何"
    },
    "OptionDescribe":{
        "1":"选择当前课程的任课老师",
        "2":"满分10分 最低分1分",
        "3":"满分10分 最低分1分",
        "4":"满分10分 最低分1分",
        "5":"满分10分 最低分1分",
        "6":"满分10分 最低分1分",
        "7":"满分10分 最低分1分",
        "8":"满分10分 最低分1分",
        "9":"满分10分 最低分1分",
        "10":"满分10分 最低分1分"
    } ,
    "QuestionnaireOption":{
        "1":{
            "2":"1"
        },
        "2":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "3":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "4":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "5":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "6":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "7":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "8":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "9":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        },
        "10":{
            "1":"1",
            "2":"2",
            "3":"3",
            "4":"4",
            "5":"5",
            "6":"6",
            "7":"7",
            "8":"8",
            "9":"9",
            "10":"10"
        }
    } 
}



//新增问卷调查
###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "QuestionnaireTheme" :"教师满意度调查问卷",
    "QuestionnaireTitle" : "XX学院XX月教师满意度调查问卷",
    "QuestionnaireQuestion":"{|dwad|:|请选择你的任课老师|}",
    "OptionDescribe":"请选择你的任课老师",
    "QuestionnaireOption":"请选择你的任课老师"
}