@url = http://localhost:5003

### 查询获取所有角色
GET {{url}}/role HTTP/1.1

### 模糊查询
GET {{url}}/role?keyword=管理 HTTP/1.1

### 添加角色
POST {{url}}/role HTTP/1.1
Content-Type: application/json

{
    "RoleName":"宿舍管理员"
}

### 修改角色
PUT {{url}}/role/50f65b8e-dbd4-4990-9533-845f9a69d0d9 HTTP/1.1
Content-Type: application/json

{
    "RoleName":"宿舍管理员"
}

### 删除角色
DELETE {{url}}/role/50f65b8e-dbd4-4990-9533-845f9a69d0d9 HTTP/1.1