@url=http://localhost:5003/teacher


//教师列表
###
GET {{url}} HTTP/1.1

//模糊查询
###
GET {{url}}?keyword=蒋昊雅 HTTP/1.1

//添加教师
###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "TeacherName":"侯丹",
    "IdNumber":"420101199307224962",
    "AcademyNum":"41",
    "sex":"女",
    "RoleName":"辅导员"
}

###
DELETE {{url}}/560dcdca-28bd-4395-8238-aaf9dd2f44ad HTTP/1.1


//修改教师信息
###
PUT {{url}}/473296ba-8529-4699-bd2b-394b6a90e08b HTTP/1.1
Content-Type: application/json

{
    "TeacherName":"李青青",
    "IdNumber":"420101198509224426",
    "qqNumber":"2222222qq",
    "weChat":"dwadwa_wexin",
    "phoneNumber":"11212121232",
    "AcademyNum":"40",
    "Sex":"女",
    "address":"非州"
}

//更新
###
PUT {{url}}/473296ba-8529-4699-bd2b-394b6a90e08b HTTP/1.1
Content-Type: application/json

{
    "TeacherName":"李青青",
    "IdNumber":"420101198509224426",
    "AcademyNum":"40",
    "Sex":"女",
    "RoleName":"辅导员"

}